# Generated by Django 5.0.6 on 2024-07-24 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.currency'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shop_address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
