# Generated by Django 5.0.6 on 2024-07-27 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_usd', models.DecimalField(decimal_places=7, max_digits=14)),
                ('date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
            ],
            options={
                'unique_together': {('currency', 'per_usd', 'date')},
            },
        ),
    ]
