# Generated by Django 5.0.6 on 2024-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='product',
            name='name_original',
            field=models.CharField(default=1, max_length=255, verbose_name='Original'),
            preserve_default=False,
        ),
    ]
