# Generated by Django 5.0.6 on 2024-08-09 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_price_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyratehistory',
            options={'get_latest_by': ['date']},
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['date'], name='idx_date'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['owner'], name='idx_owner'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['owner', 'date'], name='idx_owner_date'),
        ),
    ]
