# Generated by Django 5.0.6 on 2024-08-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_currencyratehistory_options_receipt_idx_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyratehistory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_usd',
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.product')),
            ],
            options={
                'unique_together': {('product', 'currency')},
            },
        ),
    ]
