# Generated by Django 5.0.6 on 2024-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_currency_receipt_product_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bot/'),
        ),
    ]
