# Generated by Django 5.0.6 on 2024-09-06 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_section_receipt_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('is_base', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_base_section_per_owner',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_base',
        ),
        migrations.AddField(
            model_name='sectionuser',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section'),
        ),
        migrations.AddField(
            model_name='sectionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='sections', through='main.SectionUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
