# Generated by Django 5.0.6 on 2024-07-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_receipt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='photo',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='bot/'),
        ),
    ]
