# Generated by Django 5.0.6 on 2024-09-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sectionuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='owner',
        ),
    ]
