# Generated by Django 5.0.6 on 2024-09-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_section_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='currency',
        ),
        migrations.AddField(
            model_name='sectionuser',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.currency'),
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
