# Generated by Django 5.0.6 on 2024-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
