# Generated by Django 5.0.6 on 2024-07-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
